# -*- coding: utf-8 -*-
"""2_SVM_MNIST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mon3mFxdEBRM2HlMUyfkxq0oWfJCKkr4
"""

import sys, os
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, metrics
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits

digits = load_digits()
digits.data.shape

print(digits.target)

X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, train_size = 0.2 ,random_state = 57)

"""**Linear SVM Classifier**

"""

lsc = svm.SVC(kernel='linear')

lsc.fit(X_train, y_train)

lin_y_pred = lsc.predict(X_test)

print("Accuracy :", metrics.accuracy_score(y_test, lin_y_pred))

"""**Polynominal SVM Classifier**"""

psc = svm.SVC(kernel='poly')

psc.fit(X_train, y_train)

poly_y_pred = psc.predict(X_test)

print("Accuracy :", metrics.accuracy_score(y_test, poly_y_pred))

"""**RBF SVM Classifier¶**"""

rbfsc = svm.SVC(kernel='rbf')

rbfsc.fit(X_train, y_train)

rbf_y_pred = rbfsc.predict(X_test)

print("Accuracy :", metrics.accuracy_score(y_test, rbf_y_pred))