# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xnhRRrZbYAc56RmkkPwqby2x7h1XlAbF
"""

import numpy as np
from sklearn.datasets import load_boston   #for loading the toy datasets to check our code
import matplotlib.pyplot as plt            #For ploting the graph for the better understanding of linear regression

#load_boston() returns the regression dataset
dataset = load_boston()

#dataset.data gives the features
X = dataset.data

#dataset.target gives the target values which we also called as the label for the dataset
y = dataset.target[:,np.newaxis]

print("Number of total samples in our dataset is : {}".format(X.shape[0]))
print("\n",dataset.data[0:5])

# computing cost function
def compute_cost(X, y, params):
    n_samples = len(y)
    h = X @ params
    return (1/(2*n_samples))*np.sum((h-y)**2)

# gradient descent
def gradient_descent(X, y, params, learning_rate, n_iters):
    n_samples = len(y)
    J_history = np.zeros((n_iters,1))

    for i in range(n_iters):
        params = params - (learning_rate/n_samples) * X.T @ (X @ params - y) 
        J_history[i] = compute_cost(X, y, params)

    return (J_history, params)

n_samples = len(y)

mu = np.mean(X, 0)
sigma = np.std(X, 0)

X = (X-mu) / sigma

X = np.hstack((np.ones((n_samples,1)),X))
n_features = np.size(X,1)
params = np.zeros((n_features,1))

n_iters = 1500
learning_rate = 0.01

initial_cost = compute_cost(X, y, params)

print("Initial cost : ", initial_cost, "\n")

(J_history, optimal_params) = gradient_descent(X, y, params, learning_rate, n_iters)

print("Optimal parameters : \n\n", optimal_params, "\n")

print("Final cost : ", J_history[-1])

plt.plot(range(len(J_history)), J_history, 'r')

plt.title("Convergence Graph of Cost Function")
plt.xlabel("Number of Iterations")
plt.ylabel("Cost")
plt.show()